language: java

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pv

env:
  global:
    # Make sure there is enough memory to complete the build
    - MAVEN_OPTS="-Xms1024m -Xmx2048m -Xss1m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

  matrix:
    # Unit tests
    - TEST_ARGS="-Pcompile-spec-pipelines"
cache:
  directories:
    $HOME/.m2

script:
  # Enable exit code propagation through pipes
  - set -o pipefail
  # Use pipe view (`pv`) to work around command line output timeout
  - mvn verify $TEST_ARGS | pv -t -b -l -i 10
